import json
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional

import chromadb
from chef_agent.rag.base import BaseRetriever
from chef_agent.llm.base import BaseLLM

logger = logging.getLogger(__name__)

class ChromaRecipeRetriever(BaseRetriever):
    """
    A semantic vector database retriever implementing BaseRetriever.
    Utilizes ChromaDB to store recipe documents and queries them using vector embeddings
    generated by a pluggable BaseLLM client.
    """

    def __init__(
        self,
        llm: BaseLLM,
        db_path: Optional[str] = None,
        seed_json_path: Optional[str] = None,
        client: Optional[chromadb.ClientAPI] = None
    ):
        """
        Initializes the ChromaDB client and ensures the collection is seeded.

        Args:
            llm (BaseLLM): Pluggable LLM client used to generate vector embeddings.
            db_path (str, optional): File system directory path to store ChromaDB persistent files.
            seed_json_path (str, optional): File path to recipes.json to seed the vector database if empty.
            client (chromadb.ClientAPI, optional): A pre-configured Chroma client (useful for unit testing).
        """
        self.llm = llm
        self.db_path = Path(db_path) if db_path else None
        self.seed_json_path = Path(seed_json_path) if seed_json_path else None

        # 1. Initialize client
        if client is not None:
            self.client = client
        else:
            if not self.db_path:
                raise ValueError("Either db_path or client must be provided to ChromaRecipeRetriever.")
            # Create parent directories if they do not exist
            self.db_path.parent.mkdir(parents=True, exist_ok=True)
            self.client = chromadb.PersistentClient(path=str(self.db_path))

        # 2. Get or create collection. We manually manage embeddings using our LLM client,
        # so we do not pass a default Chroma embedding function.
        self.collection = self.client.get_or_create_collection(name="chef_recipes")

        # 3. Seed database on startup if it's currently empty
        self._seed_database_if_empty()


    def _seed_database_if_empty(self) -> None:
        """Reads recipes from the seed JSON file, embeds them, and inserts them if collection is empty."""
        try:
            count = self.collection.count()
            if count > 0:
                logger.info(f"ChromaDB collection already initialized with {count} documents. Skipping seed.")
                return
        except Exception as e:
            logger.error(f"Failed to check ChromaDB document count: {e}")
            return

        if not self.seed_json_path.exists():
            logger.warning(
                f"Seed recipe database not found at {self.seed_json_path.resolve()}. "
                "ChromaDB collection will remain empty."
            )
            return

        try:
            with open(self.seed_json_path, "r", encoding="utf-8") as f:
                recipes = json.load(f)

            if not recipes:
                logger.info("Seed recipe list is empty. Nothing to insert.")
                return

            logger.info(f"Seeding ChromaDB with {len(recipes)} recipes...")

            ids = []
            documents = []
            metadatas = []

            for recipe in recipes:
                title = recipe.get("title", "")
                description = recipe.get("description", "")
                ingredients = recipe.get("ingredients", [])
                steps = recipe.get("steps", [])
                keywords = recipe.get("keywords", [])

                # Construct a rich text block representation for vector embedding semantic lookup
                doc_text = f"Recipe: {title}\nDescription: {description}\n"
                doc_text += "Ingredients:\n" + "\n".join(f"- {i}" for i in ingredients) + "\n"
                doc_text += "Directions:\n" + "\n".join(f"{idx+1}. {s}" for idx, s in enumerate(steps)) + "\n"
                doc_text += "Keywords: " + ", ".join(keywords)

                # ChromaDB metadata values must be simple types (str, int, float, bool).
                # We serialize list structures to JSON strings.
                metadata = {
                    "title": title,
                    "description": description,
                    "ingredients": json.dumps(ingredients),
                    "steps": json.dumps(steps),
                    "keywords": ",".join(keywords)
                }

                recipe_id = recipe.get("id") or f"recipe_{hash(title)}"
                ids.append(recipe_id)
                documents.append(doc_text)
                metadatas.append(metadata)

            # Generate embeddings in batch using the LLM client
            logger.info("Generating embeddings for recipes...")
            embeddings = self.llm.get_embeddings(documents)

            # Insert into database
            self.collection.add(
                ids=ids,
                documents=documents,
                embeddings=embeddings,
                metadatas=metadatas
            )
            logger.info(f"Seeding successful. Added {len(recipes)} documents to ChromaDB.")

        except Exception as e:
            logger.error(f"Failed to seed ChromaDB vector database: {str(e)}", exc_info=True)

    def retrieve(self, query: str, limit: int = 3) -> List[Dict[str, Any]]:
        """
        Embeds the query text and retrieves matching recipes via semantic cosine similarity.

        Args:
            query (str): Natural language search terms.
            limit (int): Maximum recipes to return.

        Returns:
            List[Dict[str, Any]]: List of matching recipes formatted as standard dict structures.
        """
        if not query:
            return []

        try:
            count = self.collection.count()
            if count == 0:
                logger.debug("ChromaDB collection is empty, returning no results.")
                return []
        except Exception as e:
            logger.error(f"Failed to query ChromaDB count: {e}")
            return []

        try:
            # 1. Embed query using pluggable LLM
            query_embeddings = self.llm.get_embeddings([query])
            if not query_embeddings:
                return []
            query_vector = query_embeddings[0]

            # 2. Query the Chroma collection
            results = self.collection.query(
                query_embeddings=[query_vector],
                n_results=limit
            )

            retrieved_recipes = []

            # 3. Process matches (results['metadatas'] is a List[List[Dict]])
            if results and results.get("metadatas") and len(results["metadatas"]) > 0:
                match_metadatas = results["metadatas"][0]
                match_ids = results["ids"][0]

                for idx, meta in enumerate(match_metadatas):
                    # Unpack metadata fields
                    ingredients = []
                    steps = []
                    keywords = []

                    if "ingredients" in meta:
                        try:
                            ingredients = json.loads(meta["ingredients"])
                        except Exception:
                            pass
                    if "steps" in meta:
                        try:
                            steps = json.loads(meta["steps"])
                        except Exception:
                            pass
                    if "keywords" in meta:
                        keywords = [k.strip() for k in meta["keywords"].split(",") if k.strip()]

                    recipe = {
                        "id": match_ids[idx],
                        "title": meta.get("title", ""),
                        "description": meta.get("description", ""),
                        "ingredients": ingredients,
                        "steps": steps,
                        "keywords": keywords
                    }
                    retrieved_recipes.append(recipe)

            return retrieved_recipes

        except Exception as e:
            logger.error(f"Error executing ChromaDB retrieval: {str(e)}", exc_info=True)
            return []

    def add_recipe(self, recipe: Dict[str, Any]) -> None:
        """
        Embeds the recipe text content and upserts it into the Chroma DB collection.

        Args:
            recipe (Dict[str, Any]): Recipe dict containing title, ingredients, etc.
        """
        title = recipe.get("title", "")
        if not title:
            logger.warning("Attempted to add a recipe with no title to ChromaDB. Skipping.")
            return

        description = recipe.get("description", "")
        ingredients = recipe.get("ingredients", [])
        steps = recipe.get("steps", [])
        keywords = recipe.get("keywords", [])

        # Construct a rich text representation to generate vector embedding for semantic search
        doc_text = f"Recipe: {title}\nDescription: {description}\n"
        doc_text += "Ingredients:\n" + "\n".join(f"- {i}" for i in ingredients) + "\n"
        doc_text += "Directions:\n" + "\n".join(f"{idx+1}. {s}" for idx, s in enumerate(steps)) + "\n"
        doc_text += "Keywords: " + ", ".join(keywords)

        # Serialize list fields to JSON strings for Chroma metadata storage
        metadata = {
            "title": title,
            "description": description,
            "ingredients": json.dumps(ingredients),
            "steps": json.dumps(steps),
            "keywords": ",".join(keywords)
        }

        recipe_id = recipe.get("id") or title.lower().strip().replace(" ", "-")

        try:
            # 1. Generate embedding using pluggable LLM
            embeddings = self.llm.get_embeddings([doc_text])
            if not embeddings:
                logger.error(f"Failed to generate embedding for recipe '{title}'. Upsert aborted.")
                return
            vector = embeddings[0]

            # 2. Upsert (inserts if new, updates if ID exists)
            self.collection.upsert(
                ids=[recipe_id],
                documents=[doc_text],
                embeddings=[vector],
                metadatas=[metadata]
            )
            logger.info(f"Successfully upserted recipe '{title}' to ChromaDB.")
        except Exception as e:
            logger.error(f"Failed to upsert recipe '{title}' to ChromaDB: {e}", exc_info=True)

